### ISSUE TITLE
Publish 1.3.36 (misspublished AngularJS version)

### ISSUE THREAD

**Issue by pisaacs** [hiravgandhi/angularjs-rails#76]
The AngularJS team inadvertently published 1.3.6 as 1.3.36. Consequently, 1.3.36 of angularjs-rails was also published.  

Related issue: https://github.com/hiravgandhi/angularjs-rails/issues/74

https://code.angularjs.org/

```
1.3.36/                                            09-Dec-2014 00:11                   -
...
1.3.6/                                             09-Dec-2014 00:26                   -

```

**Comment by brookisme** [comment]
When I run bundle install it gets set to 1.3.36 in my Gemfile.lock.  This works locally, but deploying on Heroku fails:

       Fetching gem metadata from https://rubygems.org/...........
       Could not find angularjs-rails-1.3.36 in any of the sources
       Bundler Output: Fetching gem metadata from https://rubygems.org/...........
       Could not find angularjs-rails-1.3.36 in any of the sources
 !
 !     Failed to install gems via Bundler.
 !

 !     Push rejected, failed to compile Ruby app

**Comment by pisaacs** [comment]
1.3.36 was yanked (https://rubygems.org/gems/angularjs-rails/versions) - isn't a valid angularjs version.

**Comment by brookisme** [comment]
Thats what I figured, the problem is that it keeps ending up in my
Gemfile.lock

From my gemspec...

  s.add_dependency 'angularjs-rails', '~>  1'
  s.add_dependency 'angular_rails_csrf', '~> 1'


Everytime I run bundle install.  1.3.36 reappears in my Gemfile.lock

I've tried deleting my Gemfile.lock and running bundle update.  Ultimately
to deploy I am forced to manually edit the Gemfile.lock

**Comment by pisaacs** [comment]
See http://stackoverflow.com/questions/24028605/rails-heroku-unable-to-git-push-heroku-master-i18n-issue

Hope this helps.

**Comment by brookisme** [comment]
It did! Thanks
